spring.application.name=product-service


server.port=8082


# Enable automatic restart and live reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
springdoc.cache.disabled=true


# MongoDB connection configuration
spring.data.mongodb.uri=mongodb://localhost:27017/ekart-product
spring.data.mongodb.database=ekart-product
spring.data.mongodb.auto-index-creation=true
spring.datasource.hikari.minimum-idle=5

#enabling global level logging
logging.level.com.raju.product=DEBUG
logging.level.root=INFO


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

jwt.secret=Y1Pz7W+SliTLD2pO+nW8d1QEjFR7r/iZYvTxbhcpIq8=
dss.app.jwtExpiration=86400000

#managing schemas section in swagger-ui 
# -1 : hide
# 0 : collapse
# 1 : show (default)
springdoc.swagger-ui.default-models-expand-depth=1

#File-Server Location Path
#file.Server.LocationPath =  /home/ubuntu/
file.Server.LocationPath =  /home/user/

#SMS
sms_api_key = expat1api
sms_api_secret = y57Kd@Xrz2ZD

